[project]
name = "dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.9",
    "discord-ext-voice-recv>=0.5.2a179",
    "discord-py[voice]>=2.7.1",
    "dotenv>=0.9.9",
    "huggingface-hub>=1.23.0",
    "moonshine-voice>=0.0.69",
    "openai>=2.46.0",
    "prompt-toolkit>=3.0.52",
    "pynacl>=1.5.0",
    "scipy>=1.17.1",
    "silero-vad>=6.2.1",
    "torch==2.11.0",
    "torchaudio==2.11.0",
    "torchvision==0.26.0",
    "transformers>=5.14.1",
]
